### ISSUE TITLE
ACL manager is logging invalid characters

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico#106]
There are some ACL manager logs with invalid characters in them. This may not be a complete list, and worth a trawl through to fix. The following are good examples.

    2015-01-14 11:22:09,331 [INFO] calico.acl_manager.acl_publisher 93: ACL Manager received packet {u'issued': 1421234529336.414, u'type': u'GETACLSTATE', u'endpoint_id': u'e8c43c84379a'} from  ^@k\213Ej
    2015-01-14 12:04:44,516 [INFO] calico.acl_manager.acl_publisher 97: Received query message ['\x00k\x8bE\xac', '', '{"issued": 1421237084520.584, "type": "GETACLSTATE", "endpoint_id": "e8c43c84379a"}'] from Felix
    2015-01-14 12:04:44,516 [DEBUG] calico.acl_manager.acl_publisher 108: Sending response message:

**Comment by neiljerram** [comment]
What do you think is invalid here?

------------------

**Comment by plwhite** [comment]
`\x00k\x8bE\xac` does not look like useful information. Annoyingly, I had truncated the first line which had another crazy unprintable string in it, but have fixed that now.

**Comment by neiljerram** [comment]
I suspect it's the zmq connection ID, though.

------------------

**Comment by Lukasa** [comment]
Correct. That is actually fine, because it's emphatically *not* a string. That's just how Python prints bytestrings: it treats them as ascii-ish. It's a bit weird that it's five bytes, but hey, that's how it goes.

The 'from' in the above line seems weird though.

**Comment by plwhite** [comment]
Putting non-printable characters into logs is not a good idea (for example, grep doesn't work on ACL manager log files unless you give it some extra arguments), and the fact that there is nothing in the logs to say who the ACL manager is talking to is really bad too. I think the connection ID is not what the code means to log; it is probably trying to log the ID (hostname) of the remote entity (which it has available to use).

This bug is making diagnosis of the connection issues we've seen quite a lot harder, incidentally. Feels to me like a must fix for the next release.

**Comment by neiljerram** [comment]
I think you're misunderstanding the situation here, and that this is actually not a bug at all.

Firstly, there are not any non-printable characters in the log.  The log contains an entirely printable sequence of characters: \, x, 0, 0, k, etc. that _represents_ some characters (that _were_ unprintable) in the bytestream.  In other words, Python has already handled the unprintability for us.  This part of the log may still _look_ unprintable, but it actually isn't.

Secondly, the conceptual data being logged is the content of a 0MQ message.  When an application (such as ACL manager here) uses a ROUTER socket, and that socket receives a message, 0MQ passes up a multipart message, whose first part identifies the peer that sent the message - using the characters that this issue is discussing - and whose third part is the data that the peer sent.  That's just what 0MQ does, and I think it makes perfect sense for ACL Manager to log out that complete message.

I agree with you that the receiving application should ideally then log a more intelligible representation of the sending peer - such as the peer's IP address or hostname - but that should be  in addition to the message logging that we're seeing here, not instead of it.

**Comment by neiljerram** [comment]
Oops - just saw Cory's prior comment about the 'from' line.  I agree with that, as that would be an example of 'the receiving application should ideally then log a more intelligible representation of the sending peer'.  And also the characters in _that_ line look as though they probably were logged unprintably...

So if this issue is all about fixing the 'from' log line, I'm happy with that.

**Comment by plwhite** [comment]
Worth clarifying that the characters are not printable. They are not; they were made printable by me typing out the visual representation of the binary bytes in emacs.

**Comment by Lukasa** [comment]
Fix available in #123.
