### ISSUE TITLE
Felix needs to respond faster to ENDPOINT* messages.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#142]
On slow systems, Felix can cause problems by blocking its responses to ENDPOINT* messages behind doing work. This is particularly problematic on ENDPOINTCREATED messages, where ipsets and iptables programming occurs before Felix responds.

Arguably, Felix should do as much as it can to give it confidence that it can program the interface before responding, but by the time we're putting iptables rules in we're surely pretty confident we can program it!

This has caused problems when running on VMs: see metaswitch/calico-docker#2.

**Comment by neiljerram** [comment]
Also please recall that we decided some time ago that Felix would only ever respond negatively to an ENDPOINT* request if there was something immediately wrong about the request, e.g. a missing field or syntax error.

Now this does not imply that Felix should respond instantly - but it is consistent with that, because it means that there is no reason for Felix to delay responding in order to check for some complex potential error condition.

------------------

**Comment by plwhite** [comment]
I think it makes sense to respond immediately, but it's not clear it helps in general. Suppose a resync is going on - the plugin is going to be throwing creates at Felix as fast as it can. If Felix responds OK, then goes and works for 15 seconds, it just means it is the next cycle that hits the problem.

We either need to restructure to make Felix threaded, or we need to do something more clever with keepalive messages and logic.

**Comment by neiljerram** [comment]
Agreed.  I think this is the point of https://github.com/Metaswitch/calico/issues/143.

**Comment by plwhite** [comment]
Superseded by PR #307
