### ISSUE TITLE
Add net-tools to list of RHEL dependencies.

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#146]
Per Spike Curtis' post on the mailing list here, we require the `arp` tool for Felix's correct operation, which is potentially not present on CentOS (and therefore RHEL). We should extend our list of dependencies to cover it.

@matthewdupre, I'm assigning to you because you're working in this area.

**Comment by neiljerram** [comment]
Obviously should do this for Debian/Ubuntu too.

Also - just in case - I presume "We should extend our list of dependencies to cover it." means _technically_, rather than that we should just document this.  In other words, this should be an addition to a Depends: line in debian/control, and to a Requires: line in rpm/calico.spec.

**Comment by Lukasa** [comment]
Correct. =)
