### ISSUE TITLE
VMs took a long time to become pingable

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#160]
I created 2 VMs on my calico deployment, running an Ubuntu 1404 cloudimage, modified to enable IPv6.  I sshed into both VMs successfully using their IPv6 addresses.  I then attempted to ping between them, which failed.  I left the VMs alone for a while.  Much later, I observed that pings were now working.

What's causing the slow setup?

**Comment by lwr20** [comment]
diags tarballs on calico-jenkins:/usr/share/nginx/www/diags/160/  
VMs were created at 09:40:22.  Ping was successful at 11:05.

There are 2 resyncs between these times at 1016 or 1046 - presumably one of these 'fixed' the problem.

**Comment by Lukasa** [comment]
This is almost certainly blocked behind a known dnsmasq issue. There's a fix upstream in dnsmasq.

**Comment by Lukasa** [comment]
The relevant fix is [this one](http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=393415597c8b5b09558b789ab9ac238dbe3db65d), should be in the next released version of dnsmasq. The issue is the result of a recent nova patch I made that regressed DHCPv6 support temporarily to improve live migration.
