### ISSUE TITLE
Plugin doesn't send update when adding a Security Group to a VM

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#163]
I've got a bunch of VMs in 2 separate groups.  They each have a rule allowing ping to work within the group.  I grab one VM from one group and add the second group to it.  It should now be able to ping all the VMs in both groups - but it cannot ping the ones in the group it has just been added to.

**Comment by lwr20** [comment]
Looking at /var/log/neutron/server.log, I can see the ID of the VM's port in 3 GROUPUPDATEs, but these are all for the same group (same group ID).  I would have expected to see a GROUPDATE including this port in the other group.

Suggests a problem with the plugin.

diags copied to calico-jenkins/diags/163

**Comment by lwr20** [comment]
VM has IP address 10.65.0.48 and port ID 078c0f5d-ae7c-4543-a755-4c71330025ee.

**Comment by neiljerram** [comment]
This could be a similar (apparent) DB caching issue, like the one I think I'm seeing in the VM migration issue.

------------------

**Comment by neiljerram** [comment]
Actually no, not DB caching at all.  I had a quick close look at this yesterday, and it turns out the plugin is just wrong in its expectation of how a change like this will be signaled.

- What it expects: that CalicoNotifierProxy.security_groups_member_updated() will be called.

- What actually happens: update_port_postcommit() is called for the relevant port.  One of the available dict keys for the port is 'security_groups', so I presume that a change there can be detected by comparing context.original['security_groups'] and context.current['security_groups'].

So the fix is (I guess) to add code into update_port_postcommit() to detect changes in the SG set, and to call CalicoMechanismDriver.send_sg_updates() for the new or removed SG IDs.

**Comment by fasaxc** [comment]
@Lukasa , presumably this is fixed in the HA plugin, which does everything differently?

**Comment by matthewdupre** [comment]
@Lukasa - any idea whether this is still likely to be an issue?

**Comment by lwr20** [comment]
I can confirm that this is working regularly in our FV runs.  So its probably no longer an issue :)
