### ISSUE TITLE
Coding style?

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#177]
Should we standardise/publish our coding style so that external contributors know how to format the code?  

I'd be strongly inclined to abandon the "#**********************#" comment blocks and ' '-aligned assignments in favour of standard PEP-8 comments, docstrings et al.  One of the design principles of Python is that vertical space is precious so wasting lines on asterisks is an anti-pattern (and they're really awkward to work with without our internal macros).  It also puts a burden on external contributors.

Also needs to be clear which variant of docstring we're expecting.

**Comment by fasaxc** [comment]
While I'm at it, for our previous project, we settled on a line length of 99 chars, which the vast majority of us preferred over the default 79/80.

**Comment by Symmetric** [comment]
Might be worth considering adding linting into the project from the get-go -- capable python IDEs such as PyCharm support pep8 reformatting, and this could be folded into the build process too (i.e. the build fails when all (or some) pep8 moans are raised).

This was a complete non-starter in our previous project since retroactively reformatting code would be dull and time-consuming, but if we start early, we could stay on top of this.

FWIW, go sidesteps the whole formatting debate by strongly encouraging all projects use their auto-fomatter "gofmt" (e.g. by a git pre-commit hook) so in most cases formatting is a non-issue. I think that's a sensible way of sidestepping the inevitable bikeshedding on this subject.

**Comment by Lukasa** [comment]
My honest position is that I don't care what we choose.

I agree with @Symmetric that style is largely a bikeshed (see also: this issue!). The problem with it is that  no-one wants *just* PEP8 as enforced by a PEP8 linter out-of-the-box. Line length is a good example, where every PEP8 linter will by default enforce 79 chars, but Shaun (and presumably others) would prefer going to 99 chars. This means that even saying "we will just do PEP8" is insufficiently specific, because people will want their exemptions.

I'm open to trying to flesh this out into something concrete, but I recommend waiting until we're in person to do it, because GitHub issues are too low-bandwidth for this conversation.

**Comment by fasaxc** [comment]
@Lukasa, the link to the other issue didn't show up and I couldn't find another issue that mentioned coding style.  Sadly, I can't make the UK meeting due to prior commitments so I'll throw in my 2p now and let you guys hash it out in Enfield:

Alright, I've got a bee in my bonnet about the boxed comments; apart from the vertical space issue, my personal reason is that they're really tedious to maintain and tie us to particular editors that have macros defined.  However, I've also been briefed to give our codebase a look over as an "outside contributor" and look out for gotchas that would trip up someone external and I think asking people to use the boxed style would make some friction.

(I think we took the average of team preference to reach 99.  @Symmetric wanted 150 IIRC, I was has happy with 79.)

I'm not bothered for going as far as enforcing PEP-8  with a linter.  Apart from the boxed comments and "aligned assignments", nothing jumped out in the felix code base.  It's close enough.  The only other thing my PEP-8 linter is complaining about is the odd missing line of whitespace.  As long as we don't have factions where one removes the whitespace as cleanup and the other adds it back, I don't care!

**Comment by Symmetric** [comment]
Agree that this bears a more in-depth discussion.

To close the loop on one of the points raised here though, I'll just add here that the pep8 tool does support custom line-widths (it's one of the few things that's [configurable](1)), so we'd not be off-piste if we decreed  `pep8 --max-line-length=99` to be the canonical style for the project. Maybe there are other rules that folk would want to suppress too, but I can't think of any myself.

@fasaxc - my preference was for 120, but 99 is a great improvement over 79 IMO.

[1]: http://pep8.readthedocs.org/en/latest/intro.html#example-usage-and-output

**Comment by Lukasa** [comment]
Ok, so I think the consensus is to wait until most of you are in Enfield in the coming weeks and find a time to discuss it (I nominate a slot in the pub, because frankly I think most of us will need a drink for this discussion...). We should aim to timebox as well, to avoid this descending into some kind of bikeshed painting madness.

**Comment by alexaltair** [comment]
Tentative agenda:
* comment style
* docstring style
* line lengths
* using PEP8
* using a commit-hook linter
* vertically-aligned argument lists

**Comment by Lukasa** [comment]
We've resolved this.
