### ISSUE TITLE
Calico repo uses mixed line endings

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#182]
Some are Windows CRLF, some are Unix-style LF-only.  Given that Calico is a native Linux project, I suggest we standardise on Unix-style and Windows users use the recommended "check out Windows-style, commit Unix-style" option.

Here's github's take on it: https://help.github.com/articles/dealing-with-line-endings/  Looks like we can check in a .gitattributes file that will configure git correctly for whatever we decide.

**Comment by Lukasa** [comment]
No disagreement here. I never noticed because my text editor doesn't care, but we should make sure everyone checks their machines are correctly configured.

**Comment by plwhite** [comment]
I actually disagree, I think. I think all the files should be checked out linux format, and checked in linux format. That's because I expect files checked out on a windows box being in linux format when I sync them to a linux test box for testing, and also because I may check out on windows and check back in on linux or vice versa because of cygwin.

I'm also personally very wary about automatic line ending changes because I have seen them corrupt binary files (though not with git, so maybe it's smarter than the dumb tools I have used in the past).

On the other hand, I agree that the Unix file ending type is the correct one for all code files!

**Comment by fasaxc** [comment]
I do all my dev work on Ubuntu so unix line endings all the way is fine by me.  That said, I know the auto setting is the recommended/default way to set up git on Windows when you install via the install wizard.
