### ISSUE TITLE
Security hole in dhcp iptables rule

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#196]
Currently, this rule is always assigned to a VM, regardless of security policy:
-A felix-from-dcf2bb9c-19 -p udp -m udp --sport 68 --dport 67 -j RETURN

The problem with this rule is that it does not specify any source and/or destination, so certain traffic could be allowed to/from the public internet (assuming that the IP assigned to the VM is public) on those ports, even if the security policy is setup to disallow that.  While they are typically used only for DHCP, this does not prevent someone from setting up a different service using these ports to get around security policies.

I believe a better rule would be something like:
-A felix-from-dcf2bb9c-19 -p udp -m udp -s 0.0.0.0 --sport 68 -d 255.255.255.255 --dport 67 -j RETURN

This rule should prevent off-subnet use.  This rule doesn't catch all DHCP traffic, but the rest (that has the actual IP as the source address) would get allowed by the other rules.

**Comment by Lukasa** [comment]
This feels like a good adjustment Nick, mind opening a GitHub issue?

Cory

**Comment by Lukasa** [comment]
Agreed, this is a definite bug.

**Comment by Lukasa** [comment]
We can actually do better here *in principle*. We should really only allow DHCP traffic destined for the local host, so really it shouldn't enter the FORWARD chain at all. There's a limitation in our iptables programming here that we can't specify that, which is a much more substantial enhancement that I don't really want to worry about right now, but we should consider it for the future.

**Comment by Lukasa** [comment]
And actually that's what we have to do. An *initial* DHCP request will look like the above (source IP 0.0.0.0, destination IP 255.255.255.255), but subsequent ones will not. In particular, DHCP renewals will be IP unicast (so won't match destination IP) and will have their current IP in place.

Therefore, I think the *actual* solution to this bug is to split out the INPUT and FORWARDING chains, which we probably should have done a long time ago.

**Comment by fasaxc** [comment]
This has languished, we should address it.

**Comment by Lukasa** [comment]
So the *right* fix here is to split the INPUT/FORWARD chains into two separate ones. Sadly, while conceptually simple, this will touch a *lot* of the Felix code and is really a pretty substantial refactor.

The other option is to always allow DHCP requests aimed at the box from a tap interface. That will work just fine, because we allow compute hosts unrestricted ability to respond to their hosted entities. This means that we can pull the special-case code out and allow any DHCP request (including DHCPv6) from any compute host. Simple.

For the moment, for the sake of efficiency, I'm going to pursue option two. Someone more comfortable with the Felix iptables code should separately think *really hard* about whether or not it makes sense to separate the INPUT and FORWARD chains, and in particular whether it makes any sense for the VM's security rules to go into the INPUT chain (where I'd argue it does not).
