### ISSUE TITLE
Calico will use iptables-restore, which can clobber changes from other processes

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#320]
Per https://github.com/Metaswitch/calico/pull/307 I see that work is being done to use iptables-restore instead of the iptables command.

Unfortunately this presents a race condition where changes could be done by another process (our system has iptables rules that are managed by another process) between the time that the iptables-save and iptables-restore commands were ran.  While this may happen quickly, having the possibility of this race is not acceptable when system correctness is required. The iptables-restore command only lets you restore at the table, not chain, level.  Therefore it doesn't seem possible to make use of iptables-save/iptables-restore in this manor.

It seems like the best approach would be to use the python-iptables module (which should offer both performance and be race-free), however that was removed previously.

**Comment by plwhite** [comment]
I want to discuss this more internally here, but two comments.

* We've found in practice that python-iptables was quite a lot slower than running iptables-restore (it seems that it reads the entire state in each time it runs and then reapplies it for each change, and while you can turn that commit behaviour off we've hit problems doing so).

* I agree with the general point about correctness, but we are planning to run iptables-restore with the noflush option. In other words, we never use iptables-save at all; if we want to change the contents of a chain we just generate an iptables-restore file for that single chain and apply it. That means that there should be no clash with another process (unless it is completely rewriting the entire state, or changing the Felix specific chains, neither of which we would expect).

Does that make sense?

**Comment by nbartos** [comment]
I admit I didn't read much of the code, I saw iptables-save used here:
https://github.com/Metaswitch/calico/pull/307/files#diff-f1e5cabd734561a57e0c54ee6b4467ceR153

But now I see it doesn't look like that output is used to directly pass into iptables-restore.

Now that you mentioned --noflush, I do realize I may have had incorrect assumptions about it.  My thought was that --noflush wouldn't allow you to delete the previous contents of a chain (thus making it only useful for adding to a chain), but now I realize one could simply just flush or delete a single chain as one of the commands.

That does make sense, and as long as that works as advertised, I withdraw my objection.

**Comment by fasaxc** [comment]
Hi Nick, I've been involved in making the switch to iptables-restore and I investigated the behaviour of `iptables`/`iptables-restore` under concurrency as part of the design work.  

I just wanted to flag up that, while felix is robust to concurrent access (it will detect concurrent access and retry), running `iptables-restore` can cause other concurrent `iptables` commands to fail.  This is because both `iptables` and `iptables-restore` do a read-modify-write of a whole netfilter table and they detect concurrent access only when they try to do their write.   Sadly `iptables-restore` doesn't respect the xtables global lock (as used by `iptables --wait`) so we may still have an issue here if you're relying on that.  (Without the `--wait` option, iptables still tries to grab the lock but it fails with an error immediately if it can't acquire it.)

Please can you clarify what tables you're accessing and what tools you're using to manipulate them?  Are you relying on the "--wait" option of iptables?

**Comment by nbartos** [comment]
We are currently using iptables directly without --wait.  However, I don't think it would be too much work for us to use iptables-restore with a retry to handle concurrency issues.

**Comment by fasaxc** [comment]
In case it's useful, I've pushed my rough-and-ready test script for testing concurrent `iptables`/`iptables-restore` here: https://github.com/Metaswitch/calico/blob/smc-check-ipt-script/calico/felix/test/check_iptables.py.

It's missing a test to verify that `iptables` fails due to concurrent `iptables-restore` commit but I couldn't think of a way to reliably hit that window.

**Comment by nbartos** [comment]
Thanks, that will help.

**Comment by plwhite** [comment]
I think we've agreed that this is OK to close. @nbartos, if I'm misrepresenting you please reopen!
