### ISSUE TITLE
Add ability to override felix.cfg with environment variables

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#326]
This makes it much easier to configure felix when it's running under a docker container.

**Comment by neiljerram** [comment]
Isn't felix.cfg already obsolete now?  I thought it had been entirely replaced by the ../config parts of the etcd data model.

**Comment by neiljerram** [comment]
Oh, I see.  We're still using felix.cfg for settings involved in connecting to etcd in the first place.

I think that now leaves us with a rather confusing overall config model, and that we should consider streamlining it.  IIUC, we now have:

- a hardcoded /etc/calico/felix.cfg (which could be problematic, e.g. if someone wanted a trial install under /usr/local) ...

- ... from which we read 3 values: EtcdPort, EtcdHost and FelixHostname

- environment variables that may override those 3 values from felix.cfg

- all other config read from Etcd.

(We also used to have a --config-file command line option, but I see that's been removed.)

I suggest the following.

- We don't need felix.cfg anymore.  Let's just allow environment variables to override the coded defaults for EtcdPort, EtcdHost and FelixHostname.

- It looks to me as though we might not need Felix-specific env vars for EtcdPort and EtcdHost.  https://coreos.com/docs/distributed-configuration/etcd-configuration/ documents an ETCD_ADDR variable.  AFAICS this is currently honoured by the etcd server (and proxy?), not by the etcd client library or by python-etcd; but I don't see why we couldn't use the same name and make Felix honour it.  (We could do that either at the Felix level, or by submitting a patch to python-etcd.)

- If using the same name doesn't feel quite right, I think it would still be good to follow their convention of a single var specifying both host and port, instead of two separate vars.

- Any Felix-specific env vars that we honour should definitely include 'FELIX' or 'CALICO'.

If you agree, that boils down to just 2 Felix-specific vars: FELIX_HOSTNAME and FELIX_ETCD_ADDR.  Or possibly 1 Felix-specific (FELIX_HOSTNAME) and 1 compatible honouring of ETCD_ADDR.

**Comment by fasaxc** [comment]
I don't think environment variables play nice with the OpenStack approach, which is all config-file based.  @plwhite @Lukasa do you have an opinion?  Using a config file wasn't a decision I was part of; I'm just maintaining the status-quo there.

I was keen to make the environment variables able to override any of the config in that file rather than special-casing just a few cases.  (I'd forgotten about the FelixHostname variable, but my code still handles it so I think that was the right design choice.)

Combining into one variable and prefixing with FELIX or CALICO sound like good ideas.  I'll make those changes.

We lost the ability to specify the config file when we moved to python 2.6.  I've filed #329 to cover that since it's orthogonal to this pull req.

**Comment by Lukasa** [comment]
I see no reason not to allow both a config file and environment variables, allowing the environment to override the config file. Make the config file optional and then we can look like the etcd-style model (command line args and environment vars) and the OpenStack model (configuration files).

**Comment by neiljerram** [comment]
In general, though, we shouldn't just keep stuff because we can, should we?  I'd say we need a positive reason _for_ keeping a config file and that, if we don't have one, we should enjoy the code simplification to be gained from discarding it.

**Comment by plwhite** [comment]
I think the positive reason is that the install code uses it now. If we could do that install another easier way, then I'm happy to nuke the config file.

**Comment by neiljerram** [comment]
I've prepared a code change to nuke the config file at https://github.com/Metaswitch/calico/pull/366.

**Comment by neiljerram** [comment]
@fasaxc Coming back to your original premise: "This makes it much easier to configure felix when it's running under a docker container."  Why is that?

**Comment by fasaxc** [comment]
That's due to dockers file-system architecture.  It downloads a snapshot file system and runs the application on top of it.  The snapshot is mainly read-only (in any case it's hard to modify from outside the container).

Files that the container does need to share (e.g. its persistent data files) are mounted into the container as volumes. 

That's overkill for "bootstrap" config so they've settled on a de-facto standard of passing in environment variables.

Tentatively closing this, please re-open if you think that's premature...
