### ISSUE TITLE
Dig into: Felix incorrectly times out when watching etcd, events delayed until subsequent poll

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#359]
This one is a ship-stopper.

If a poll times out client-side, it looks like python-etcd or urllib3 is reusing the TCP connection and doing HTTP pipelining.  Of course, that's totally broken because the previous request is a long poll so pipelining behind it delays the response until the previous request finishes.  It doesn't seem to handle the subsequent response correctly either.

@spikecurtis and I are investigating, aiming to put in a workaround today, which will probably involve forcing a reconnection from our side.

**Comment by fasaxc** [comment]
I merged the workaround but I think we need to do more digging and really understand what's going wrong in urllib3/python-etcd before we can close this one.

**Comment by Lukasa** [comment]
urllib3 is not strictly pipelining, it's engaging in HTTP/1.1's standard connection reuse pattern. Pipelining is when you issue many requests one after another without reading responses, while connection re-use involves reading the entire response before issuing the next request.

The problem here appears to be that urllib3 is not considering the exception that busts the long poll to be a connection-breaking event. What exception is hit?

**Comment by neiljerram** [comment]
Is this still a concern or not?  There's a "fix available" label, so does that mean this issue can be closed?

On the other hand, if there is still a problem, will progress be made on it in time for 0.17?

**Comment by fasaxc** [comment]
We have a workaround in place and I've read the urllib3/httplib code for the versions that we're using and it appears that they don't catch the socket timeout, which is the case that we hit after all the fixes related to this.  I believe the confusion came from running tests against unexpected urllib3 versions that do catch that exception and wrap it.

I'm pretty happy to close this for now.  There's a future enhancement to use the streaming API that would be great but that's orthogonal.
