### ISSUE TITLE
Make configuration composable from multiple sources

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#407]
Felix now expects the metadata address to be in etcd but the plugin isn't writing it there.

**Comment by fasaxc** [comment]
A customer hit this and it's blocking them; I've offered them a patch that reinstates the old behaviour (loading from the config file) while we get this sorted.

**Comment by fasaxc** [comment]
The customer says that, in their infrastructure, the metadata IP will be different on each node and it's not known by neutron.  I'm wondering whether we need to be flexible about where we get our configuration from in order to support such cases.  How about we use the same key names in the config file, etcd (global and per-host scopes), and our environment variables (for docker support) and inherit missing config from further up the hierarchy:

* environment variables trump all (only used in docker or manual execution so feels like these should win)
* config file trumps etcd config
* per-host etcd config trumps global etcd config
* global etcd config has lowest priority.

**Comment by Lukasa** [comment]
I can get behind this principle, except that the relationship between per-host ETCD config and the config file seems wooly. There's no obvious stable ordering there. Any reason we shouldn't use something like confd to ensure that the two data sources are forcefully kept in sync?

**Comment by neiljerram** [comment]
Some details that I don't understand here...

- Firstly, what precisely is the Metadata configuration requirement? In the absence of any configuration, I believe the default is localhost:8775. Is the customer's requirement here to have the metadata API running on just one node, and hence to require a specific IP instead of localhost? Does that IP need to change dynamically during the life of the cluster? 

- Secondly, I believe the architecture now is (a) for such configuration to be provided, where necessary, via the etcd data model (instead of felix.cfg); (b) to regard the etcd data model as a public API that Calico customers / integrators can write to, in addition to (say) the OpenStack plugin writing to it.

Hence, if a particular deployment requires metadata <addr> and <port>, I thought the architecture for that would be for that deployment to do

    etcdctl set /calico/v1/config/MetadataAddr <addr>
    etcdctl set /calico/v1/config/MetadataPort <port>

Is there something about that picture that is wrong, or that doesn’t meet the customer requirement? 

Certainly we could also add a plugin setting, to get it to set these values, but I don't think that's necessary. And I don't understand at all why it's being discussed to reintroduce felix.cfg settings.

**Comment by neiljerram** [comment]
I understand now that the requirement is for the metadata IP to be different on different compute hosts. In that case the architected solution (as I understand it) is for the deployment to set /calico/v1/host/<hostname>/config/MetadataAddr to the desired value, for each <hostname>.

**Comment by neiljerram** [comment]
Sorry, markup glitch. That key should be:

    /calico/v1/host/<hostname>/config/MetadataAddr

**Comment by fasaxc** [comment]
@Lukasa agree, there's no obviously right ordering between config file and etcd.  My reasoning was that etcd is transient and so writing anything into that is non-trivial; it requires handling the case where etcd needs to be rebuilt.  If etcd overrides the config file then we need to make sure that the most specific corner cases are covered by the code that writes into etcd, whereas if the config file overrides etcd, we can make deployment-specific tweaks more easily.  If we do have the code in place to do the overrides in etcd then there's no need to write anything into the config file so just don't use it.

@neiljerram etcd isn't the master datastore in OpenStack so who writes that data?  If it's the plugin, then it needs a second master database of the relevant IPs (this particular customer is using the local routable IP of the host rather than binding to localhost).  Another customer might use an IP we haven't thought of.

**Comment by apollitt** [comment]
I agree @fasaxc that the etcd data store is not the master data store in many cases.  In OpenStack it is a key part of our architecture that etcd can be blown aware at will and the OpenStack plug-in will repopulated it with Felix and other listeners being robust to that happening (i.e. in networking terms, graceful restart with non-stop forwarding rather than non-stop routing).

I'm also curious whether this is case of Felix having OpenStack specific configuration.  If so that feels wrong to me long term, though I don't think it should hold up the release (and may not even need resolving in 1.0 timeframe so long as we are all clear about any compromises we are therefore making,  what our long term plan is and how we will get there).

**Comment by matthewdupre** [comment]
Do we really need different metadata IPs on different compute nodes?  That wasn't my understanding of this requirement.

**Comment by plwhite** [comment]
There's an interesting question here - which component owns writing the configuration into etcd? If that's the plugin, fine - but I'm not sure that it actually is. If it isn't, then there's a question of what the process to nuke and rebuild looks like.

**Comment by Lukasa** [comment]
I'm pulling this issue out of 0.16 and renaming it.

The original report in this issue, that the metadata address and port could not be configured, is not valid: they can, via etcd. This issue has now turned into allowing multiple configuration sources and composing them together. It's a worthy goal, but not for 0.16.

For the moment I'm punting to 0.17, but if this doesn't get picked off the pile by then I'll punt to 1.0.

**Comment by lxpollitt** [comment]
Here's my 2 pence worth on this one:  The original report was not invalid.  The customer is an OpenStack based deployment using our plug-in.  In that scenario our design goal was that the use of etcd should be as transparent as possible.  In particular, it is not the master data store so can be blown away at anytime (e.g. the 3am support call), and the customer does not need to manage data in etcd themselves (the plug-in does this behind the scenes).  As I understand it, we recently moved the metadata configuration from a local file to etcd only.  That does not fit with our design goals and I think is a valid bug.

@plwhite - In an OpenStack deployment the plug-in is responsible for populating etcd (except for the bits that Felix updates to report back state of course).

@Lukasa - I'm fine with broadening the issue to address config more holistically (I think that's a good thing).  But I don't want the validity of the original issue to get lost.  At this stage I expect that (even taking into consideration my 2 pence worth of comments above) it's too late to change this back to 0.16, but shout if not.

**Comment by nbartos** [comment]
Just a couple of notes since this discussion started because of me:

1.  The requirement for having a different metadata IP on each node should no longer be necessary.  I dug into why we were doing this, and apparently it's no longer necessary because we're no longer supporting the thing that required it.  Binding to 127.0.0.1 should be fine going forward.

2.  In the larger/future picture, I do like being able to make runtime config changes via etcd.  However as mentioned, currently we will be running etcd in a ramdisk and therefore it's volatile.  It would be tricky to get config changes back in after the backing data is destroyed.  I think it's definitely necessary to have some sort of host based config that isn't in etcd.  Right now I'm battling the same issue with the log settings.  The log settings are an interesting case, since they should be applied before any logging would be possible, e.g. before any connection attempts (which generate useful logs) would be made to etcd.

**Comment by plwhite** [comment]
I have a fix for this in branch issue407config - but it breaks a couple of UTs, so I'll have to wrap it up tomorrow.
