### ISSUE TITLE
Improve logging of etcd error conditions

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#458]
The plugin uses some broad except blocks to catch, for example, etcd connection failures during resync.  We just log out the exception but often that doesn't make it clear what the impact is.  For example, @nbartos hit this one during an FV run:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/calico/openstack/t_etcd ", line 88, in periodic_resync_thread
  File "/usr/lib64/python2.7/site-packages/calico/openstack/t_etcd.py", line 333, in provide_felix_config
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 349, in read
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 586, in api_execute
  File "/usr/lib64/python2.7/site-packages/etcd/client.py", line 541, in _next_server
EtcdException: No more machines in the cluster
```

It'd be much cleaner if we logged that this exception terminated the resync and that we'll retry.  Even better if we could catch common exceptions explicitly and log appropriate errors/warnings.

**Comment by neiljerram** [comment]
In general, seeing an exception traceback in the log should be interpreted as that we _are_ probably handling it!  Note that if an exception is raised that we _don't_ catch, it causes the greenlet to terminate, without any logging.

For this particular log, I'm afraid I don't yet understand what "No more machines in the cluster" really means - and hence what is really the best way to log and handle that situation.  Can anyone else advise?

**Comment by Lukasa** [comment]
> In general, seeing an exception traceback in the log should be interpreted as that we are probably handling it! Note that if an exception is raised that we don't catch, it causes the greenlet to terminate, without any logging.

Please don't do that. If an exception is an indication of normal flow (e.g. nothing is inherently wrong), don't log the traceback.

Put another way, logging a traceback at any level lower than WARNING is *definitely* wrong, and doing it at any level lower than ERROR is *probably* wrong.

Tracebacks stand out very clearly in logs, and so we should only attract attention to them if they're almost certainly a symptom of the problem.

**Comment by neiljerram** [comment]
Sorry, I wasn't clear.  By 'handling it' above, I just meant 'preventing the thread from silently dying' - and hence that perhaps there isn't a strong reason for adding _another_ log to say "it's OK, the periodic resyncs will continue'.  Clearly, this isn't 'handling it' in the sense of actually understanding what it means :-)

As soon as I understand what "No more machines in the cluster" really means, and when it can occur, I will completely agree with you that we should replace the exception logging (for that case) with something more meaningful.  I would still like to keep a catch-all exception log for anything else, because I'd prefer to see an exception in the log - for unanticipated exceptions - than nothing at all.

**Comment by nbartos** [comment]
My opinion is that tracebacks should definitely be used in all unexpected error cases, but only in unexpected error cases (or the rare case when it's an expected error but you need a stack trace).  In expected error cases, the tracebacks should be replaced with an appropriate log message.

For example, it seems icky to have a traceback in the case of a database disconnect, when the code handles the reconnect properly.  Instead of a traceback, a single warning log message similar to "Lost database connection to %s, will reconnect." should be used.

**Comment by ed-harrison** [comment]
+1

**Comment by neiljerram** [comment]
I believe we're all in agreement on the principle here.  My comment above @nbartos's one was intended to say the same thing, but @nbartos expressed it rather better!

Regarding the specific problem of "No more machines in the cluster": I've just reviewed this again with @Lukasa and we plan no action for the time being.  We believe that "No more machines in the cluster" occurs when the local etcd proxy is having trouble communicating with the non-proxy instances of the etcd cluster; and we don't yet understand in more detail why that is.  It definitely seems right to catch this exception and allow the resync thread to run again later - as the current code does - but on the other hand it definitely _isn't_ a known-benign problem, so it makes sense for now to leave the exception logging in place, so that we will continue to be alerted when this is happening.

**Comment by nbartos** [comment]
I should note that we are running only a single instance of etcd (master elected and backed with a ramdisk), with both neutron and felix pointing directly to that instance without any etcd proxies.  I'm not sure if that changes your thoughts on why it's coming up in this case.

**Comment by matthewdupre** [comment]
For another one, we saw the following log while the controller (with the etcd cluster) was rebooting.  This is misleading and excessively scary.

```
http://calico-jenkins:8080/view/Testing/job/run-long-tests/30/testReport/%3Cnose/suite/ContextSuite_...
=== LOG 2015-06-18 03:14:44 ERROR [pid 23819] ===
calico.felix.fetcd 371: Unknown etcd error "Server response was not valid JSON: ValueError('No JSON object could be decoded',)"; doing resync.
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/calico/felix/fetcd.py", line 329, in _wait_for_etcd_event
check_cluster_uuid=True)
File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 357, in read
return self._result_from_response(response)
File "/usr/lib/python2.7/dist-packages/etcd/client.py", line 537, in _result_from_response
'Server response was not valid JSON: %r' % e)
EtcdException: Server response was not valid JSON: ValueError('No JSON object could be decoded',)```

**Comment by Lukasa** [comment]
Renamed this because several of the issues discussed here actually affect Felix, not the plugin.

**Comment by fasaxc** [comment]
@neiljerram For context: "No more machines in cluster" is a poor error message from python-etcd.  It happens when python-etcd's retry code gets invoked, which tries the request against a different node in the cluster and then it runs out of nodes to try.  The original cause of the retry (usually a connection failure or timeout) is the more interesting thing but that is lost because the retry code raises its own error.

**Comment by fasaxc** [comment]
I don't think this made it into 0.27.

**Comment by alexwlchan** [comment]
I have also been seeing the "No more machines in cluster" exception when the etcd disk is full. We can definitely provide a more useful message than that.

(Scale testing, with a single node in the etcd cluster. I stuffed it full of endpoints until it ran out of space, and then this exception bubbled up.)

**Comment by Lukasa** [comment]
Ok, I think there's only one actual high-priority issue in here, which is the 'no more machines in cluster' error. I'm going to track that separately in #721, and otherwise I think we have nothing else to do here.
