### ISSUE TITLE
KeyError in plugin while trying to create VMs during FV run

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#489]
The bobcat's FV rig reported this error:

```
2015-04-29 18:55:02,549 [ERROR][22365] calicotest.common.testutils 87: Hit unexpected exception in function - not retrying.
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/fv-tests/calicotest/common/testutils.py", line 84, in retry_until_success
    result = function()
  File "/var/lib/jenkins/workspace/fv-tests/calicotest/openstack/vm.py", line 259, in raise_unless_state
    raise VmErrorState("VM is in state 'ERROR' and must be "
VmErrorState: VM is in state 'ERROR' and must be deleted.
ERROR
2015-04-29 18:55:39,038 [INFO][22365] calicotest.openstack.topology 321: Running TestBasicNetworks.setUpClass
```

which coincided with this stack trace in the neutron server.log (note: the logs are in different timezones):

```
2015-04-29 10:55:00.954 1018 WARNING urllib3.connectionpool [-] HttpConnectionPool is full, discarding connection: localhost
2015-04-29 10:55:00.955 1018 ERROR neutron.plugins.ml2.managers [req-211ac354-831f-45cc-8b49-ef32c847a422 None] Mechanism driver 'calico' failed in create_port_postcommit
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers Traceback (most recent call last):
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/neutron/plugins/ml2/managers.py", line 168, in _call_on_drivers
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers     getattr(driver.obj, method_name)(context)
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 139, in create_port_postcommit
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers     self.transport.endpoint_created(port)
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 294, in endpoint_created
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers     self.write_profile_to_etcd(profile_id)
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 263, in write_profile_to_etcd
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers     json.dumps(self.profile_rules(profile_id)))
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers   File "/usr/lib/python2.7/dist-packages/calico/openstack/t_etcd.py", line 271, in profile_rules
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers     for rule in self.sgs[sgid]['security_group_rules']:
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers KeyError: u'092b94fa-44c9-479f-9064-6ebd9a01f264'
2015-04-29 10:55:00.955 1018 TRACE neutron.plugins.ml2.managers 
2015-04-29 10:55:00.956 1018 ERROR neutron.plugins.ml2.plugin [req-211ac354-831f-45cc-8b49-ef32c847a422 None] mechanism_manager.create_port_postcommit failed, deleting port 'cef93584-eef8-4f68-a6d4-80fbb6fcd05d'

```

The full log is at http://calicobobcat-jenkins.gulfstream:8080/job/fv-tests/767/console

**Comment by fasaxc** [comment]
@neiljerram I don't think it's efficient for me to look into this one, please can you dig into it tomorrow?  I'll send you the full log file.

**Comment by robbrockbank** [comment]
Looks related to #465 
https://github.com/Metaswitch/calico/issues/465

**Comment by Lukasa** [comment]
It's also related to #482, which sees a similar traceback.

**Comment by Lukasa** [comment]
So this set of errors all fundamentally occur because we're looking for a security group that the plugin doesn't know anything about.

Basically what happens here is that the neutron plugin stores information about security groups internally, in a dictionary. This dictionary is populated in two ways: first, by a call to `resync_security_groups`, which is made from the periodic resync thread; and second, by a call to `security_group_updated`, which is called whenever the `CalicoNotifierProxy` is told about changes to security group membership or rules.

The specific error is occurring when we try to write a new profile to etcd during endpoint creation.

The profile I'm seeing in the log I'm looking at is made up of a single security group: 092b94fa-44c9-479f-9064-6ebd9a01f264. We look to find that security group, and it's missing, so we fall over.

After some conversation with Neil, we believe there are three major changes we need to make here:

1. The order of operations in the plugin resync thread is wrong. We first provide Felix config (including the ready flag), then write in data for the endpoints, then write in data for the security groups. These operations should probably be entirely reversed: security groups first, then endpoints (as they rely on having security group data available), and then the ready flag. Note that some Felix config probably really does want to go in early, and that should be written first, so this may spread out to four steps instead of three.
2. While we're resyncing security groups, it's possible that we will process an endpoint creation event that references a security group that has not yet been written to etcd. To resolve this, we should either:
    1. Always write security profile information into etcd whenever it's needed (expensive).
    2. Read etcd to confirm that the security profile information is up to date, then write it if it isn't (still quite expensive, also high latency).
    3. Prevent endpoint creation events until after start-of-day sync is complete, but otherwise allow them (runs the risk of stale data, but will at perform best).
    4. Some other compromise solution (more regular security group resync, etc.)
3. In a HA solution, the security group cache simply doesn't work, as not all security group updates go through all plugin instances. The plugin needs to be improved to retrieve data from the database as it needs it.

I'll open appropriate GitHub issues for these things.

**Comment by Lukasa** [comment]
Ok, the more I think about this the more I think the Neutron driver has fundamentally got a poor architecture for dealing with security groups in a HA environment. Requiring it to keep the full state of endpoints and security profiles in memory is untenable, and doesn't scale at all. I think it needs rearchitecting to avoid keeping snapshots of state in memory.

**Comment by Lukasa** [comment]
Alright, in the short term I'm going to open a few patches that should paste over areas where I believe this can happen. None of these will correctly solve the underlying problems, but they should buy us a bit more time.

The first case is any major action that occurs before start of day processing is complete: in particular, endpoint create and update actions. This can be solved by holding up any such action until start-of-day processing is complete: this is done in #501. I believe this is the issue reported here.

The second case is any situation where there is a race between us finding out about security group changes and endpoint actions. We can improve this by simply allowing a fixed number of retries to any endpoint creation action, which I'll be opening a PR for shortly. I believe this is the issue reported in #465.

To be clear, none of this actually resolves the problem: they're all just band-aids on some of the manifestations of the problem that I believe we've seen.

**Comment by fasaxc** [comment]
There are customers hitting this in the field so I've marked it as a ship-stopper.  I think fixing this is much more important than shipping 0.18 on time.

**Comment by Lukasa** [comment]
@fasaxc I disagree, sadly.

Fixing this properly in the general case is several weeks of work, and it benefits no-one to block other patches behind it. On the other hand, #501 and #502 should do a good job of ameliorating the effects in the short term, and so are probably good enough.

**Comment by fasaxc** [comment]
@Lukasa let's not try to solve all these long-term issues at the same time.  

There must be something that we can do that gets the code correct and scalable _enough_ for the time being.  For example: if it came down to it, catching that exception and triggering a full resync in 5 seconds would be better than dying in a heap!  (Neil seemed concerned that the simple retries in #502 wouldn't have the desired effect.)

**Comment by Lukasa** [comment]
> There must be something that we can do that gets the code correct and scalable enough for the time being.

Yes, I can throw out the flow model that the entire section of code is supposed to do and simply force a resync in any VM create/update scenario. That's the only way to get the code *correct*, though I believe the jury's out on 'scalable' in that case.

Anything else has edge-cases in correctness where we can end up claiming that we successfully programmed an endpoint that is entirely unreachable. I would argue that's worse than claiming we failed to program an endpoint that *is* reachable, where the only cost is retrying that programming.

I think there's FUD over #502 that is unjustified. There's only one outstanding question in my mind which is about DB transactions. Otherwise, a situation where a VM is added to a security group and we don't get told about it within 1s seems like it *ought* to be an error case to me. I'll defer to you in this case though, as you're the one who has to answer to the customer.

**Comment by fasaxc** [comment]
I think I've gotten to the bottom of a class of issues in the plugin that all affect the non-HA case.  Agree that the HA case needs more substantial thought.

My hunch is that the plugin was written under the assumption that eventlet uses cooperative multi-threading, which is true... ...except when it's using monkey_patching or when we do IO.  Neutron *does* use monkey-patching and we *do* do IO (to access etcd) so the cooperative assumption doesn't hold.  that implies that we need proper synchronisation between our resync and main thread.

**Comment by Lukasa** [comment]
> My hunch is that the plugin was written under the assumption that eventlet uses cooperative multi-threading, which is true... ...except when it's using monkey_patching or when we do IO. Neutron does use monkey-patching and we do do IO (to access etcd) so the cooperative assumption doesn't hold. that implies that we need proper synchronisation between our resync and main thread.

I think you and I understand co-operative concurrency differently. Even with the monkeypatching, the concurrency is still co-operative, because a thread of execution cannot be *forced* to yield. With monkeypatching in place, however, the yield points are implicit. This implicit cooperative concurrency is a paradigm I *loathe* (gevent does it too), partly because it inevitably causes problems of this form. Give me Twisted's `@inlineCallbacks` or asyncio any day of the week.

A short-term plaster for this problem can involve adding the synchronization you've added in #508, so let's move forward with that for now.

:disappointed:

**Comment by neiljerram** [comment]
I believe we're done on this now, after merging @fasaxc's PR.  Please shout and reopen if I've got that wrong.
