### ISSUE TITLE
Port BIRD anycast changes from calico-docker

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#510]
As discussed in #350, felix now supports enough anycast for calico-docker.  However, they had to make local BIRD config changes to get BIRD to program multiple routes.  We should investigate and incorporate into our canned BIRD config.

**Comment by ed-harrison** [comment]
@Symmetric Can you recall what the specific BIRD config changes were that you needed?  Was it just the "add paths on" configuration, or was there more to it?

**Comment by matthewdupre** [comment]
I don't see why we'd make a change to our BIRD config to support anycast, when as far as I'm aware it's currently impossible to set that up in OpenStack?  Am I missing something here?

**Comment by lxpollitt** [comment]
Is the BIRD config we are talking about scoped only at OpenStack?  If it is just part of the standard calico repo then potentially people doing integration with other orchestrators would use it.

**Comment by matthewdupre** [comment]
This kind of BIRD config change would go into calico-chef (OpenStack specific), and into the templates used by the calico-gen-bird-conf scripts, which I believe are also only used for OpenStack.

**Comment by fasaxc** [comment]
Sounds fine to me, let's close this.

**Comment by Symmetric** [comment]
Just got back from vacation. For the record, there are the anycast changes that we needed to do in calico-docker:

1. Remove import filters in bird config. Previously the import filter was set to be equal to the export filter, thus filtering out the routes to the spine/”internet” that were being advertised into the node. [https://github.com/Metaswitch/calico-docker/pull/80]
2. Configure add-path on the calico-node birds, since without this the bird on the higher-IP’d compute node would refuse to advertise its ECMP route (since there was a better route already, as decided by the “lowest routerID wins” tiebreaker). [https://github.com/Metaswitch/calico-docker/pull/83]
