### ISSUE TITLE
Saw master fail to renew its TTL, CaS failure

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#572]
I think I've seen the mastership bounce around after the first TTL expiry.  Manifests as a CaS failure in the master's renewal loop.

Maybe we're not specifying the right parameters to etcd?  The docs say

The directory's TTL can be refreshed by making an update. You can do this by making a PUT with prevExist=true and a new TTL.

**Comment by fasaxc** [comment]
This was with the RPMs that were built today.

**Comment by fasaxc** [comment]
Hmm, did some manual testing on the python CLI and I see the TTL get updated when I run a command like this:

```
c.write("leader", "me", ttl=180, prevValue="me")
```

**Comment by fasaxc** [comment]
After the first failure it seemed to settle down and the master happily kept renewing.  Maybe the elector was getting starved or something else?

**Comment by Lukasa** [comment]
This may be related to ongoing problems with the ready flag.

**Comment by Lukasa** [comment]
For the elector to get starved it would need to stop spinning in its loop for 30 seconds. However, that probably *can* happen if the TCP connection to etcd gets broken: the timeout is also 30 seconds. I think the etcd timeouts should probably be far shorter than the interval: say 1/5 of it? That way we'll correctly spot a dead etcd connection fast enough to ensure that we can make a good attempt at getting a write into etcd.

Also, note that when we fail to maintain the master key [in this block](https://github.com/Metaswitch/calico/blob/master/calico/election.py#L204-L209) we don't actually attempt to formally give up the mastership. This leaves us without a master for quite a while.

Any of these problems *could* be the issue, but without a log I don't know any better. And there *should* be a log, because there aren't many places where exceptions can happen in the election code.

**Comment by fasaxc** [comment]
I'll see if I can get the log from the customer.  It was a ValueError from the master's refresh loop.  The logs should let us see the timing though.

**Comment by fasaxc** [comment]
Wrote a repro script but can't seem to hit this case: https://gist.github.com/fasaxc/e8c6a7d4dfb760a61503

**Comment by fasaxc** [comment]
If we can't get a log from the customer then I suspect the only thing we can do is try to repro live in neutron in the large scale test rig.  Maybe it really is getting starved out by Neutron's start-of-day processing?

**Comment by fasaxc** [comment]
@robbrockbank one possible next action is you receiving the log from the customer.

**Comment by Lukasa** [comment]
Currently this is blocked as we have no repro and no logs. Removing this from 0.21 until we can unblock it.

**Comment by matthewdupre** [comment]
Similarly removing from 1.0, we can't fix it without something to go by.

**Comment by fasaxc** [comment]
I don't think we're going to get those logs, lets close unless we see this again.
