### ISSUE TITLE
Diags collection script

### ISSUE THREAD

**Issue by lwr20** [Metaswitch/calico#68]
I got tired of collecting the wrong diags for issue #67, so I wrote a shell script to do it for me.  

I'm not claiming this is perfect, but it gives us something to add to whenever diags are insufficient. :)

**Comment by neiljerram** [comment]
First I think we should code manage this somewhere, as that will help further review and enhancement.  I suggest creating a 'tools' or 'utils' subdir in the Calico repo, and adding this script in there.

Secondly I wonder if we can rely on iptables-save, which will do a more complete job than the current iptables invocations in this script.  I think we can, on the grounds that we can ensure that iptables-save is available on any of our test machines, and document the requirement for others.

That's all the script comments I have for now.  I guess the next thing after that would be automation so that it actually runs, and so that the logs are made available via the Jenkins UI.

**Comment by Lukasa** [comment]
This was merged in as part of #125, so this can be closed.

However, Nick Bartos has provided some good enhancements: see the linked issue to track those.
