### ISSUE TITLE
ZMQError: Interrupted system call

### ISSUE THREAD

**Issue by nbartos** [Metaswitch/calico#76]
Opening a bug report per recommendation on the mailing list.

I am using branches based on the calico nova & neutron master branches.  The OS is custom, not related to either Ubuntu or Redhat.

Everything is running on a single node, of IP address 10.45.0.5.

After installation, I first create a network inside a project.  Then, when attempting to launch a VM attached to the network, I receive the following error.

```
Dec 22 21:33:44.094536 127.0.0.1 neutron-server[6557]: neutron.plugins.ml2.drivers.mech_calico/INFO: [req-5b0c3d2d-531d-4456-882d-d9035fd614cb None] => Outbound Calico rule {'protocol': None, 'cidr': '::/0', 'group': None, 'port': None}
Dec 22 21:33:44.094698 127.0.0.1 neutron-server[6557]: neutron.plugins.ml2.drivers.mech_calico/INFO: [req-5b0c3d2d-531d-4456-882d-d9035fd614cb None] Neutron rule {'remote_group_id': u'3904347b-f3c9-4872-82c2-25ae7339c5e3', 'direction': u'ingress', 'remote_ip_prefix': None, 'protocol': None, 'ethertype': u'IPv4', 'tenant_id': u'07772f83f8784a3183d46afef0260d69', 'port_range_max': None, 'port_range_min': None, 'id': u'f4b3649a-5c09-4e51-9bc9-625f3ee1ba9b', 'security_group_id': u'3904347b-f3c9-4872-82c2-25ae7339c5e3'}
Dec 22 21:33:44.094851 127.0.0.1 neutron-server[6557]: neutron.plugins.ml2.drivers.mech_calico/INFO: [req-5b0c3d2d-531d-4456-882d-d9035fd614cb None] => Inbound Calico rule {'protocol': None, 'cidr': None, 'group': u'3904347b-f3c9-4872-82c2-25ae7339c5e3', 'port': None}
Dec 22 21:33:44.096500 127.0.0.1 neutron-server[6557]: neutron.plugins.ml2.drivers.mech_calico/INFO: [req-5b0c3d2d-531d-4456-882d-d9035fd614cb None] Endpoints for SG 3904347b-f3c9-4872-82c2-25ae7339c5e3 are {}
Dec 22 21:33:44.096721 127.0.0.1 neutron-server[6557]: neutron.plugins.ml2.drivers.mech_calico/INFO: [req-5b0c3d2d-531d-4456-882d-d9035fd614cb None] Sending GROUPUPDATE: {'rules': {'inbound': [{'protocol': None, 'cidr': None, 'group': u'3904347b-f3c9-4872-82c2-25ae7339c5e3', 'port': None}, {'protocol': None, 'cidr': None, 'group': u'3904347b-f3c9-4872-82c2-25ae7339c5e3', 'port': None}], 'outbound': [{'protocol': None, 'cidr': '0.0.0.0/0', 'group': None, 'port': None}, {'protocol': None, 'cidr': '::/0', 'group': None, 'port': None}], 'outbound_default': 'deny', 'inbound_default': 'deny'}, 'group': u'3904347b-f3c9-4872-82c2-25ae7339c5e3', 'type': 'GROUPUPDATE', 'members': {}, 'issued': 1419284024096.519}
Dec 22 21:33:44.098788 127.0.0.1 neutron-server[6557]: neutron.api.v2.resource/ERROR: [req-5b0c3d2d-531d-4456-882d-d9035fd614cb None] delete failed
neutron-server[6557]: neutron.api.v2.resource/TRACE: Traceback (most recent call last):
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/api/v2/resource.py", line 87, in resource
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/api/v2/base.py", line 454, in delete
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/plugins/ml2/plugin.py", line 750, in delete_port
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/db/securitygroups_rpc_base.py", line 123, in notify_security_groups_member_updated
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/plugins/ml2/drivers/mech_calico.py", line 731, in security_groups_member_updated
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/plugins/ml2/drivers/mech_calico.py", line 709, in send_sg_updates
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/neutron/plugins/ml2/drivers/mech_calico.py", line 644, in send_group
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/eventlet/green/zmq.py", line 312, in send_multipart
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 258, in send_multipart
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "/usr/lib64/python2.7/site-packages/eventlet/green/zmq.py", line 288, in send
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "socket.pyx", line 571, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5319)
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "socket.pyx", line 618, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5086)
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2081)
neutron-server[6557]: neutron.api.v2.resource/TRACE:   File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6032)
neutron-server[6557]: neutron.api.v2.resource/TRACE: ZMQError: Interrupted system call
```

The only error message in the Calico logs is this (which probably shouldn't be):

```
[ERROR] calico.felix.felix 70: Felix starting
```
```
# cat neutron.conf 
[DEFAULT]
# Since we currently have only a single router in a single namespace, overlapping IPs will not work in
# the majority of cases.  Once we have multiple routers and router namespaces, we should be able to set
# this to true.
allow_overlapping_ips = false
api_workers = 5
bind_host = 10.45.0.5
bind_port = 9696
core_plugin = neutron.plugins.ml2.plugin.Ml2Plugin
host = 10.45.0.5
lock_path = $state_path/lock
# These are only fallback logging strings.  All daemons should override them with appropriate names.
logging_context_format_string = "neutron[%(process)d]: %(name)s/%(levelname)s: [%(request_id)s %(user_identity)s] %(instance)s%(message)s"
logging_default_format_string = "neutron[%(process)d]: %(name)s/%(levelname)s: %(instance)s%(message)s"
logging_exception_prefix = "neutron[%(process)d]: %(name)s/TRACE: %(instance)s"
notification_driver = neutron.openstack.common.notifier.rpc_notifier
service_plugins = neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
syslog_log_facility = LOG_DAEMON
use_stderr = false
use_syslog = true
verbose = true

rabbit_host = 10.45.5.1
rabbit_port = 5672
rabbit_userid = rabbit-mq-user
rabbit_password = something
rabbit_virtual_host = /

# This is icky, but the URL expected is not the same one published by keystone exactly,
# and using the nova v3 compute URL results in a traceback.
nova_url = http://nova.piston:8774/v2
nova_region_name = RegionOne
nova_admin_username = neutron
nova_admin_password = something
nova_admin_tenant_name = service
nova_admin_auth_url = http://keystone.piston:5000/v2.0

[agent]
get_datapath_retry_times = 30
root_helper = sudo neutron-rootwrap /etc/neutron/rootwrap.conf

[keystone_authtoken]
admin_password = something
admin_tenant_name = service
admin_user = neutron
auth_uri = http://10.45.6.2:5000/v2.0
identity_uri = http://keystone.piston:35357

[database]
connection = mysql://mysql_svc:something@10.45.5.2/neutron?connect_timeout=10&read_timeout=60
idle_timeout = 120
max_pool_size = 2
max_retries = -1
retry_interval = 3
max_overflow = 20
pool_timeout = 120
use_db_reconnect = true
db_retry_interval = 3
db_inc_retry_interval = false
db_max_retry_interval = 3
db_max_retries = -1

[ml2]
type_drivers = local, flat
mechanism_drivers = calico

[securitygroup]
enable_security_group = true


# cat /etc/acl_manager.cfg 
[global]
# Plugin address
PluginAddress = 10.45.0.5

[log]
# Log file path.
LogFilePath = /var/log/calico/acl_manager.log


# cat /etc/felix.cfg  
[global]
# Time between retries for failed endpoint operations
#EndpointRetryTimeMillis = 500
# Time between complete resyncs
#ResyncIntervalSecs = 1800
# Plugin and ACL manager addresses
PluginAddress = 10.45.0.5
ACLAddress    = 10.45.0.5
# Metadata IP (or host) and port. If no metadata configuration, set to None
#MetadataAddr  = 127.0.0.1
#MetadataPort  = 9697

[log]
# Log file path.
LogFilePath = /var/log/calico/felix.log
# Log severities for the Felix log and for syslog.
LogSeverityFile   = INFO
#LogSeveritySys    = ERROR
LogSeverityScreen = CRITICAL

[connection]
# Time with no data on a connection after which we give up on the
# remote entity
#ConnectionTimeoutMillis = 40000
# Time between sending of keepalives
#ConnectionKeepaliveIntervalMillis = 2000


# cat nova.conf
[DEFAULT]
firewall_driver = nova.virt.firewall.NoopFirewallDriver
network_api_class = nova.network.neutronv2.api.API
neutron_admin_auth_url = http://keystone.piston:5000/v2.0
neutron_admin_password = something
neutron_admin_tenant_name = service
neutron_admin_username = nova
neutron_auth_strategy = keystone
neutron_metadata_proxy_shared_secret = something
neutron_url = http://neutron.piston:9696/
security_group_api = neutron
service_neutron_metadata_proxy = True
allow_resize_to_same_host = True
allow_same_net_traffic = False
api_paste_config = /etc/nova/api-paste.ini
auth_strategy = keystone
ca_path = /etc/nova/CA
cobalt_outgoing_migration_address = 10.45.0.5
cobalt_use_image_service = True
compute_driver = libvirt.LibvirtDriver
config_drive_format = vfat
console_host = 10.45.0.5
cpu_allocation_ratio = 16.0
ec2_dmz_host = 10.45.0.5
ec2_host = 10.45.0.5
ec2_listen = 10.45.0.5
enable_new_services = False
enabled_apis = ec2,osapi_compute,metadata
force_config_drive = always
force_raw_images = False
glance_api_servers = 10.45.0.5:9292
host = 10.45.0.5
image_cache_manager_interval = 40
instance_name_template = instance-%08x
instances_path = /mnt/novadisk/nova/instances
keys_path = /etc/nova/keys
keystone_ec2_url = http://keystone.piston:5000/v2.0/ec2tokens
lock_path = /var/lock/nova
metadata_listen = 10.45.0.5
multi_host = True
my_ip = 10.45.0.5
novncproxy_base_url = http://10.45.6.4:6080/vnc_auto.html
novncproxy_host = 10.45.6.4
novncproxy_port = 6080
openstack_user = nova
osapi_compute_extension = cobalt.nova.osapi.cobalt_extension.Cobalt_extension
osapi_compute_extension = nova.api.openstack.compute.contrib.standard_extensions
osapi_compute_listen = 10.45.0.5
quota_fixed_ips = -1
rabbit_host = 10.45.5.1
rabbit_password = something
rabbit_userid = rabbit-mq-user
remove_unused_original_minimum_age_seconds = 28800
resume_guests_state_on_host_boot = True
rootwrap_config = /etc/nova/rootwrap.conf
s3_host = 10.45.0.5
s3_listen = 10.45.0.5
s3_port = 3333
scheduler_available_filters = nova.scheduler.filters.all_filters
scheduler_default_filters = RetryFilter,AvailabilityZoneFilter,RamFilter,ComputeFilter,DifferentHostFilter,SameHostFilter,GroupAntiAffinityFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter
scheduler_driver = nova.scheduler.filter_scheduler.FilterScheduler
state_path = /var/run/nova
syslog_log_facility = LOG_DAEMON
use_cow_images = False
use_stderr = false
use_syslog = true
use_syslog_rfc_format = true
verbose = True
vncserver_listen = 10.45.0.5
vncserver_proxyclient_address = 10.45.0.5
volume_api_class = nova.volume.cinder.API
cinder_catalog_info=volume:cinder:internalURL
[conductor]
use_local = True
[database]
connection = mysql://mysql_svc:something@10.45.5.2/nova?connect_timeout=10&read_timeout=60
db_inc_retry_interval = false
db_max_retries = -1
db_max_retry_interval = 3
db_retry_interval = 3
idle_timeout = 120
max_overflow = 20
max_pool_size = 2
max_retries = -1
pool_timeout = 120
retry_interval = 3
use_db_reconnect = true
[keystone_authtoken]
admin_password = something
admin_tenant_name = service
admin_user = nova
auth_uri = http://10.45.6.2:5000/v2.0
identity_uri = http://keystone.piston:35357
[libvirt]
cpu_mode = none
images_type=lvm
images_volume_group=nova
remove_unused_resized_minimum_age_seconds = 28800
use_virtio_for_bridges = true
virt_type = kvm
```

**Comment by nbartos** [comment]
One reason was that the ubuntu branch had a patch that got applied during the build for a debian package, it wasn't applied actually in the tree.  I believe the other one was that there was a traceback that kept coming up where something was trying to access something called 'quantum', which may be some legacy code lying around from before the name change.

The messages-with-strace won't have the exception, as my later runs had a retry workaround based on the above code (but with some extra debug logging).

**Comment by nbartos** [comment]
Note:  This is the actual extra retry + debugging code that I used:

```
@@ -322,6 +324,8 @@ class CalicoMechanismDriver(mech_agent.SimpleAgentMechanismDriverBase):
                 LOG.exception("Peer is not actually available")
 
     def _get_socket_for_felix_peer(self, hostname):
+        LOG.info("_get_socket_for_felix_peer hostname = %r" % hostname)
+        LOG.info("_get_socket_for_felix_peer self.felix_peer_sockets = %r" % self.felix_peer_sockets)
         if hostname in self.felix_peer_sockets:
             return self.felix_peer_sockets[hostname]
         else:
@@ -657,8 +661,21 @@ class CalicoMechanismDriver(mech_agent.SimpleAgentMechanismDriverBase):
                'issued': time.time() * 1000}
         LOG.info("Sending GROUPUPDATE: %s" % pub)
 
-        self.acl_pub_socket.send_multipart(['groups'.encode('utf-8'),
-                                            json.dumps(pub).encode('utf-8')])
+        for n in xrange(1, 4):
+            LOG.info("acl_pub_socket.send_multipart try %d" % n)
+            try:
+                self.acl_pub_socket.send_multipart(['groups'.encode('utf-8'),
+                                                   json.dumps(pub).encode('utf-8')])
+            except ZMQError as e:
+                if e.errno == errno.EINTR:
+                    continue
+                else:
+                    raise
+            else:
+                break
+        else:
+            raise RuntimeError("All three retries hit EINTR!")
+
         LOG.info("Message sent")
 
     def _get_rules(self, sg):
```

**Comment by Lukasa** [comment]
Ok, so the first thing we need to do is use the actual OpenStack branch patches, I think. It's going to be tricky to debug when you aren't running the same code I am. =)

**Comment by nbartos** [comment]
I was using branches based on metaswitch/master for neutron and nova.  It was just the metaswitch/ubuntu* that had an issue.

**Comment by neiljerram** [comment]
Hi Nick,
I'm worried that we still haven't done a good job of explaining what branches are what in our various GitHub repositories - so I've pasted in here some text from one of our documents (that hasn't yet been published), and which tries to explain precisely this point.  Please could you take a look and let me know if it makes sense?

I should also mention some updates since the text below was written.

- For Ubuntu Trusty, our active Nova and Neutron branches are now calico_2014.1.3 (code changes) and ubuntu_2014.1.3 (packaging), based on OpenStack 2014.1.3.

- For RHEL 7 work:

  - our active Nova branch is now rhel7 (which has our code changes and packaging combined), based on OpenStack 2014.2.1

  - our active Neutron branches are calico_2014.2.1 (code changes) and rhel7_2014.2.1 (packaging), based on OpenStack 2014.2.1

Many thanks,
 Neil


==============================

# GitHub repository layouts<a id="sec-2" name="sec-2"></a>

Project Calico's open source code lives in four GitHub repositories.

-   <https://github.com/Metaswitch/calico> contains core Calico code.

-   <https://github.com/Metaswitch/calico-nova> and
    <https://github.com/Metaswitch/calico-nova> contain our forks of the
    OpenStack Nova and Neutron projects.

-   <https://github.com/Metaswitch/calico-dnsmasq> contains our fork of
    the Dnsmasq projects.

## Nova, Neutron and Dnsmasq<a id="sec-2-1" name="sec-2-1"></a>

In the repositories for code that we have forked from elsewhere, the
branch structure looks like this:

         tag:2014.1
              |       (Upstream development...)
    --*---*---*---*---*---*---*---*---*---*---*---*---*--- (upstream)
               \
                \     (Calico patches...)
                 \---*---*---*---*---*---*---*---*---*---*---*--- calico_2014.1
                  \                       \
                   \  (Debian/Ubuntu pack- \  aging and release...)
                    '---*---*-----*----*----*-----------*-----*--- ubuntu_2014.1
                        |   |     |    |    |           |     |
                  release   |  apply   | merge Calico   |    new
                   tarball  |  patches |   changes      |  release
                            |          |                |
                      Debian/Ubuntu  prepare       update and unapply
                           diffs    patch metdata    Debian patches

There will be a structure like this for each distribution base for
which we want to release a Calico variant.  For example, our work so
far has been based on the upstream's (OpenStack's) 2014.1 release for
Ubuntu, but on the upstream's 2014.1.1 release for Red Hat.  Those are
two different releases, which means that - even before we've started
to consider packaging - the Calico code changes that we make may need
to be different.

The only correct way to represent that is with a different Calico
development branch for each upstream base, and it should be accepted
that rebasing work between such branches may, in general, be
non-trivial.  Therefore, for each upstream base, identified by a tag
such as 2014.1, there is a Calico development branch named
`calico_<tag>`.

Then for Ubuntu packaging there is a branch named `ubuntu_<tag>`.
This branch adds all the `debian/` metadata, but the other key thing
about it is that all the Calico changes are represented as separate
patch files, instead of as Git-tracked changes to the affected
upstream files.  This is needed to allow comprehensible source package
uploads - e.g. to PPAs - as well as building and hosting binary
packages ourselves.

### Current branch names<a id="sec-2-1-1" name="sec-2-1-1"></a>

For both Nova and Neutron our Ubuntu Trusty-targeted packages so far
have been based on the upstream 2014.1 release, because the Ubuntu
packages when Trusty was released were:

-   Nova: 1:2014.1-0ubuntu1

-   Neutron: 1:2014.1-0ubuntu1.

Hence the `<tag>` that we're currently working with in our Nova and
Neutron repositories is `2014.1`.

We shortly need to rebase our work onto more recent versions of Nova
and Neutron that have now been released in Trusty, namely:

-   Nova: 1:2014.1.3-0ubuntu1.1

-   Neutron: 1:2014.1.3-0ubuntu1.1.

The `<tag>` when we do that work will be `2014.1.3`.

For Dnsmasq `<tag>` is `2.72`, even though the latest available Ubuntu
version in Trusty is 2.68-1, because we want more recent upstream
Dnsmasq code (because this has our first Dnsmasq patch in it) and
because it's fine (at least in this case) to prepare a forked package
that is substantially <span class="underline">newer</span> than the Ubuntu one.

(Trusty package information comes from
<https://launchpad.net/ubuntu/trusty/+source/dnsmasq>,
<https://launchpad.net/ubuntu/trusty/+source/nova> and
<https://launchpad.net/ubuntu/trusty/+source/neutron>.)

### Red Hat<a id="sec-2-1-2" name="sec-2-1-2"></a>

For now, our Red Hat packaging is based on older branches named
`master` and `rpm`, where `master` is for changes to the upstream
code, and `rpm` for packaging work.

In principle, however, the layout above should also apply to future
Red Hat packaging work.  If and when that happens, and if we are ever
targeting Ubuntu and Red Hat releases based on the same upstream base,
the work for those should share the same `calico_<tag>` development
branch.

## Calico<a id="sec-2-2" name="sec-2-2"></a>

In the repository for Calico's core code, the structure is much
simpler because we are the 'upstream' for that code, as well as being
the people trying to package and release it.  This means that we don't
need to distinguish between 'upstream' and Calico code, and also that
we can happily evolve and manage the metadata for Debian/Ubuntu and
Red Hat packaging in the same way as we do the code.

In the Calico repository, therefore, there is only a master branch,
where both development and packaging work happens.  Of course topic
and review branches are also used during development, but these are
short lived and get merged back into master, often by way of a GitHub
pull request.

**Comment by nbartos** [comment]
Thanks, that's very informative.  I received similar info from Cory a couple of days ago.  That definitely makes things easier on my end.  I will work on getting a build using the latest calico_* branches and get an strace from there.

**Comment by nbartos** [comment]
After bumping my neutron to upstream and using the latest calico and calico patches, this is no loner happening.  Therefore, I don't think it's worth investing the time to debug any further.

**Comment by Lukasa** [comment]
Fair enough. If anyone starts seeing this again we should re-open.
