### ISSUE TITLE
Felix requires ACCEPT-by-default on iptables

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#80]
As discussed in the Calico mailing list, Felix doesn't cope with iptables being set to DROP by default on the INPUT or FORWARD chains. Traffic does not get to VMs. That's obviously a problem.

We should look at enhancing Felix to program the appropriate rules in this situation.

**Comment by plwhite** [comment]
This is trivial to fix - probably worth just fixing it ASAP to get rid of it.

**Comment by plwhite** [comment]
We don't want to go nuking a compute host's security rules because that could have some serious side effects - and so we expect to document this as a manual requirement (and add an alarm so that if you get it wrong you can diagnose the problem).

To get past this on an OpenStack system you can run the following commands.

    iptables -A FORWARD -i tap+ -j ACCEPT
    iptables -A FORWARD -o tap+ -j ACCEPT
    iptables -A INPUT -i tap+ -j ACCEPT

Doing so means that traffic from / to tap interfaces (i.e. VMs) is accepted if Felix permits and no earlier rule has barred it.

**Comment by neiljerram** [comment]
In my Fuel work, I've had to add these incantations on the controller:

    # Allow BGP through the Fuel firewall
    iptables -I INPUT 1 -p tcp --dport 179 -j ACCEPT

    # Allow Calico API connections through the Fuel firewall
    iptables -I INPUT 1 -p tcp --dport 9901 -j ACCEPT
    iptables -I INPUT 1 -p tcp --dport 9903 -j ACCEPT
    iptables -I INPUT 1 -p tcp --dport 9904 -j ACCEPT
    iptables -I INPUT 1 -p tcp --dport 9905 -j ACCEPT
    iptables -I INPUT 1 -p tcp --dport 9906 -j ACCEPT

and these on each compute node:

    # Allow BGP through the Fuel firewall
    iptables -I INPUT 1 -p tcp --dport 179 -j ACCEPT

    # Allow Calico API connections through the Fuel firewall
    iptables -I INPUT 1 -p tcp --dport 9902 -j ACCEPT

This is because Fuel installs chains for INPUT that end in DENY.

**Comment by plwhite** [comment]
Key to the fix is that the chains have been restructured. The original structure was as follows.

* We used to have a `felix-INPUT` and `felix-FORWARD` chain. All INPUT packets were sent to `felix-INPUT` and all forwarded packets to `felix-FORWARD`.
* There was a per-endpoint chain for both inbound and outbound for each endpoint. These DROPPED traffic which was not allowed, and permitted other traffic.
* `felix-INPUT` and `felix-FORWARD` matched on the tap interface to send to the relevant per-endpoint chain.

The new structure is as follows.
* `felix-INPUT` and `felix-FORWARD` are gone, replaced by a new `felix-MAIN` chain. All INPUT and FORWARD packets are sent to `felix-MAIN`.
* `felix-MAIN` sends all packets that are from a `tap+` interface (i.e. an interface starting with `tap`) to a new `felix-FROM-ENDPOINT` chain, and all packets that are to a `tap+` interface to a new `felix-TO-ENDPOINT` chain. `felix-MAIN` then ends by accepting any traffic that is to or from a `tap` interface.
* The per-endpoint chains for both inbound and outbound exist exactly as before, but have moved to the `felix-TO-ENDPOINT` and `felix-FROM-ENDPOINT` chains.
* The net effect is that felix-MAIN does the following.
    * Traffic to a tap interface passes through `felix-TO-ENDPOINT`, then to the endpoint specific chain which either DROPs or RETURNs. If it RETURNs, the packet is ACCEPTed at the end of `felix-MAIN`.
    * Traffic from a tap interface passes through `felix-FROM-ENDPOINT`, then to the endpoint specific chain which either DROPs or RETURNs. If it RETURNs, the packet is ACCEPTed at the end of `felix-MAIN`.
    * Traffic that is both to and from a tap interface passes through both sets of chains, and if both RETURN then it is ACCEPTed at the end of `felix-MAIN`.
    * Traffic that is neither to nor from a tap interface passes through `felix-MAIN` without hitting any rules.

There are some simplifications we could make.

* We could get rid of `felix-MAIN` and put the rules it holds directly into `INPUT` and `FORWARD`. This won't work (because you cannot match on outbound interface in the `INPUT` chain). (It's also more complex to manage, which is a major argument against it.)
* We could remove a level of indirection by putting all of the rules in (say) `felix-TO-ENDPOINT` directly into `felix-MAIN`. That's not efficient since it means that packets will hit more rules than they need to (since we might match `eth0` against 100 tap interfaces - best to avoid if we can).
* We could have two versions of `felix-MAIN`, one for packets coming from `INPUT` and one for packets from `FORWARD`, and restrict the rules in the version of `felix-MAIN` that is used for packets from `INPUT`. However, that only saves us traversing at most two rules, at the cost of having to duplicate some chains, and so seems like premature optimisation.

Hence I think this is the right fix.

**Comment by Lukasa** [comment]
@plwhite I have a follow-on for your final point about two versions of `felix-MAIN`. What your discussion doesn't cover but might want to is that the `INPUT` and `FORWARD` chains apply to different packets. Specifically, the `INPUT` chain applies to packets destined for the compute host. It is entirely plausible that we may want to do a different kind of filtering here (e.g. DROP by default rather than ACCEPT by default) for this kind of traffic from tap interfaces.

Just something to consider.

**Comment by plwhite** [comment]
That is certainly possible. As it stands, we could implement this fairly simply by having two different versions of the `felix-MAIN` chain. That's a relatively straightforward thing to add later if we decide to do so.

**Comment by neiljerram** [comment]
FWIW, the merging of INPUT and FORWARD logic does feel a little strange to me.

**Comment by neiljerram** [comment]
I should add: all of the other details of your fix sound excellent.

**Comment by plwhite** [comment]
Note that in the end I split `felix-MAIN` into `felix-INPUT` and `felix-FORWARD`.

Fixed in PR #103
